### ISSUE TITLE
This is not good for pretending to have a img logger 👎 

### ISSUE THREAD

**Issue by efenatuyo** [scoobyluvs/Fake-img-logger#2]
There's is a much easier way and I will explain how.

create a flask app with a main route.
You will make your website embed images (make sure you link is a publish link not a local)
If someone presses on the picture the main route will be auto called.

This is much better and easier that also makes it able to be pressen by other people

**Comment by scoobyluvs** [comment]
This is not a much easier way , the code would look better , users would have more struggles.

1.) This only runs once
2.) I would have to make the flask app run 24/7 which cost.
3.) Yes , other people could press the "image logger" , but it still would return random info , not really applicable if your trying to fake an image logger
