### ISSUE TITLE
Error, installed everything thats required

### ISSUE THREAD

**Issue by ghost** [scoobyluvs/Fake-img-logger#3]
Traceback (most recent call last):
  File "directory", line 14, in <module>
    from assets.checker import Roblox
ModuleNotFoundError: No module named 'assets'

**Comment by ghost** [comment]
(Tried both Newest python and 3.9.5)

**Comment by scoobyluvs** [comment]
Could be your errors here : 

- Assets file is empty 
- its no unziped
- The folder is gone

if u just copy "main.py" and ran it , it would not work
