### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by VoltFX** [scoobyluvs/Fake-img-logger#6]
it says i should consider upgrading to via the 'c:\users\myname\appdata\local\prgrams\python\python29\python.exe -m pip install - - upgrade pip'command. and also where do i put the image and webhook?

**Comment by scoobyluvs** [comment]
1.) `consider upgrading to via the 'c:\users\myname\appdata\local\prgrams\python\python29\python.exe -m pip install - - upgrade pip` , isn't a error. 
2. ) Webhook and image are acsses via input in the script
